name: Build and deploy Node.js app to Azure Web App - ng-demo-backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20.11.1
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build (if present)
        run: npm run build --if-present

      - name: Create deployment zip
        run: |
          powershell -Command "Compress-Archive -Path * -DestinationPath app.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Azure login (federated)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_04E0DAF0E6E84A2C9EABC872B618F5B8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FF1105EF6E0D4C7D9CB568D66524BF35 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FF7CBC82ECFE4F8EBAF90F511F1E5DFE }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ng-demo-backend
          slot-name: Production
          package: app.zip
